openapi: 3.0.0
info:
  title: Queue API
  version: 1.0.0
servers:
  - url: http://127.0.0.1/
paths:
  /{queue}:
    put:
      summary: Добавление сообщения в очередь
      parameters:
        - name: queue
          in: path
          required: true
          description: Название очереди
          schema:
            type: string
        - name: v
          in: query
          required: true
          description: Текст сообщения
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Параметр v отсутствует
    get:
      summary: Получение следующего сообщения из очереди
      parameters:
        - name: queue
          in: path
          required: true
          description: Название очереди
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string